### PR TITLE
Added support for parameters

### PR DESCRIPTION
**Pull request by PtrTn**
Added support for parameters specified in https://developer.forecast.io/docs/v2#options

### CODE REVIEW

**Comment by jaimz22** [comment]
Good idea. We shouldn't be putting required parameters after optional ones though. Think you could revise your code to have `array $parameters = null`

Also it looks like your tabbing is off and the code is misaligned.

**Comment by PtrTn** [comment]
Thanks for the quick response. I've fixed both issues in commits 4ac1d4d and 7e075df.

**Comment by jaimz22** [comment]
cool. I'll probably go through and replace all the indenting with spaces just before I make the next release

**Comment by PtrTn** [comment]
Applied auto formatting in 192b5a3, should be good to go I think

**Comment by jaimz22** [comment]
@Baabah awesome thanks for going ahead and doing the auto formatting!

**Pull request merged**
